// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourDuLichASAP.API.Data;

#nullable disable

namespace TourDuLichASAP.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.AnhDoiTac", b =>
                {
                    b.Property<int>("IdAnhDoiTac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnhDoiTac"));

                    b.Property<string>("IdDoiTac")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("Date");

                    b.Property<string>("imageDoiTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAnhDoiTac");

                    b.HasIndex("IdDoiTac");

                    b.ToTable("ANH_DOI_TAC");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.AnhTour", b =>
                {
                    b.Property<int>("IdAnhTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnhTour"));

                    b.Property<string>("IdTour")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ImgTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("Date");

                    b.HasKey("IdAnhTour");

                    b.HasIndex("IdTour");

                    b.ToTable("ANH_TOUR");

                    b.HasData(
                        new
                        {
                            IdAnhTour = 1,
                            IdTour = "TDL001",
                            ImgTour = "image_0_638482704013218648.jpeg",
                            NgayThem = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7945)
                        },
                        new
                        {
                            IdAnhTour = 2,
                            IdTour = "TDL002",
                            ImgTour = "image_1_638482704145321161.gif",
                            NgayThem = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7955)
                        });
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.DanhGia", b =>
                {
                    b.Property<string>("IdDanhGia")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("DisLike")
                        .HasColumnType("int");

                    b.Property<string>("IdKhachHang")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdTour")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<string>("NhanXet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDanhGia")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDanhGia");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdTour");

                    b.ToTable("DANH_GIA");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.DatTour", b =>
                {
                    b.Property<string>("IdDatTour")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdKhachHang")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdNhanVien")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdTour")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("SoLuongNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTreEm")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDatTour")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDatTour");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdTour");

                    b.ToTable("DAT_TOUR");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.DichVu", b =>
                {
                    b.Property<string>("IdDichVu")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GiaTien")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("Date");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDichVu");

                    b.ToTable("DICH_VU");

                    b.HasData(
                        new
                        {
                            IdDichVu = "DV0001",
                            DonViTinh = "",
                            GiaTien = 500000,
                            GioBatDau = new TimeOnly(5, 0, 0),
                            GioKetThuc = new TimeOnly(20, 0, 0),
                            NgayThem = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(8060),
                            TenDichVu = "Hướng dẫn viên du lịch",
                            TinhTrang = "Đang hoạt động"
                        });
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.DichVuChiTiet", b =>
                {
                    b.Property<string>("IdDichVuChiTiet")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdDatTour")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdDichVu")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdKhachHang")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdNhanVien")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDichVu")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDichVuChiTiet");

                    b.HasIndex("IdDatTour");

                    b.HasIndex("IdDichVu");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("DICH_VU_CHI_TIET");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.DoiTac", b =>
                {
                    b.Property<string>("IdDoiTac")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<float?>("DanhGiaApp")
                        .HasColumnType("real");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("Date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenDoiTac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDoiTac");

                    b.ToTable("DOI_TAC");

                    b.HasData(
                        new
                        {
                            IdDoiTac = "DT0001",
                            DanhGiaApp = 4.5f,
                            DiaChi = "01-03 Phan Chu Trinh, Tp. Buôn Ma Thuột, Đắk Lắk",
                            Email = "sales@daklaktourist.com.vn",
                            MoTa = "Công ty chuyên về kinh doanh khách sạn, nhà hàng, khu du lịch tại thành phố Đắk Lắk.",
                            NgayDangKy = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0908116466",
                            TenDoiTac = "Công ty cổ phần Du lịch Đắk Lắk",
                            TinhTrang = "Đang hợp tác"
                        },
                        new
                        {
                            IdDoiTac = "DT0002",
                            DanhGiaApp = 4.2f,
                            DiaChi = "32 Nơ Trang Long, Tp. Buôn Ma Thuột, Đắk Lắk",
                            Email = "info@dakviettravel.com",
                            MoTa = "DakViet Travel, một địa chỉ du lịch đáng tin cậy, có trụ sở tại trung tâm của Việt Nam Tây Nguyên.",
                            NgayDangKy = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0905057890",
                            TenDoiTac = "Công ty TNHH Du lịch DakViet",
                            TinhTrang = "Đang hợp tác"
                        });
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.KhachHang", b =>
                {
                    b.Property<string>("IdKhachHang")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("Date");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("Date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("KHACH_HANG");

                    b.HasData(
                        new
                        {
                            IdKhachHang = "KH0001",
                            CCCD = "123456789012",
                            DiaChi = "123 Đường A, Quận 1, TP. HCM",
                            Email = "khachhang@gmail.com",
                            GioiTinh = "Nữ",
                            NgayDangKy = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7900),
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321",
                            TenKhachHang = "Nguyễn Thị C",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            IdKhachHang = "KH0002",
                            CCCD = "987654321098",
                            DiaChi = "456 Đường S, Quận 5, TP. HCM",
                            Email = "tvd@example.com",
                            GioiTinh = "Nam",
                            NgayDangKy = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7904),
                            NgaySinh = new DateTime(1988, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0365478912",
                            TenKhachHang = "Trần Văn D",
                            TinhTrang = "Đang hoạt động"
                        });
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.NhanVien", b =>
                {
                    b.Property<string>("IdNhanVien")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("Date");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("Date");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("Date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdNhanVien");

                    b.ToTable("NHAN_VIEN");

                    b.HasData(
                        new
                        {
                            IdNhanVien = "NV0001",
                            CCCD = "987654321098",
                            ChucVu = "Nhân viên",
                            DiaChi = "123 Lê Thánh Tông, Buôn Ma Thuột",
                            Email = "nhanvien@gmail.com",
                            GioiTinh = "Nữ",
                            NgayDangKy = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7869),
                            NgaySinh = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayVaoLam = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7878),
                            SoDienThoai = "0987654321",
                            TenNhanVien = "Trần Thị Thanh",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            IdNhanVien = "NV0002",
                            CCCD = "456789123456",
                            ChucVu = "Nhân viên",
                            DiaChi = "111 Hà Huy Tập, Buôn Ma Thuột",
                            Email = "lvc@example.com",
                            GioiTinh = "Nam",
                            NgayDangKy = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7881),
                            NgaySinh = new DateTime(1988, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayVaoLam = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7881),
                            SoDienThoai = "0365478912",
                            TenNhanVien = "Lê Văn Khánh",
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            IdNhanVien = "ADMIN1",
                            CCCD = "04883948532",
                            ChucVu = "Nhân viên",
                            DiaChi = "123 Hà Huy Tập, Buôn Ma Thuột",
                            Email = "admin@gmail.com",
                            GioiTinh = "Nam",
                            NgayDangKy = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7883),
                            NgaySinh = new DateTime(1988, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayVaoLam = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7884),
                            SoDienThoai = "0123012312",
                            TenNhanVien = "Admin",
                            TinhTrang = "Đang hoạt động"
                        });
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.ThanhToan", b =>
                {
                    b.Property<string>("IdThanhToan")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdDatTour")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdKhachHang")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdNhanVien")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.Property<int>("TongTienDichVu")
                        .HasColumnType("int");

                    b.Property<int>("TongTienTour")
                        .HasColumnType("int");

                    b.HasKey("IdThanhToan");

                    b.HasIndex("IdDatTour");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("THANH_TOAN");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.TourDuLich", b =>
                {
                    b.Property<string>("IdTour")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("DichVuDiKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("GiaTreEm")
                        .HasColumnType("int");

                    b.Property<string>("IdDoiTac")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("LoaiTour")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("Date");

                    b.Property<string>("NoiKhoiHanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhuongTienDiChuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoChoConNhan")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTreEm")
                        .HasColumnType("int");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTour");

                    b.HasIndex("IdDoiTac");

                    b.ToTable("TOUR_DU_LICH");

                    b.HasData(
                        new
                        {
                            IdTour = "TDL001",
                            DichVuDiKem = "Bữa ăn trưa, vé tham quan",
                            GiaNguoiLon = 1000000,
                            GiaTreEm = 500000,
                            IdDoiTac = "DT0002",
                            LoaiTour = "Tham quan thác",
                            MoTa = "Thăm quan thác Dray Nur nổi tiếng với khung cảnh thiên nhiên hùng vĩ, kỳ vĩ.",
                            NgayThem = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7926),
                            NoiKhoiHanh = "Buôn Ma Thuột",
                            PhuongTienDiChuyen = "Xe ô tô",
                            SoChoConNhan = 45,
                            SoLuongNguoiLon = 30,
                            SoLuongTreEm = 15,
                            TenTour = "Thác Dray Nur",
                            ThoiGianBatDau = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKetThuc = new DateTime(2024, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TinhTrang = "Đang hoạt động"
                        },
                        new
                        {
                            IdTour = "TDL002",
                            DichVuDiKem = "Hướng dẫn viên và nước uống",
                            GiaNguoiLon = 700000,
                            GiaTreEm = 300000,
                            IdDoiTac = "DT0001",
                            LoaiTour = "Thăm quan vườn cà phê",
                            MoTa = "Tham quan và trải nghiệm cuộc sống của người dân Buôn Ma Thuột tại các vườn cà phê sân vườn.",
                            NgayThem = new DateTime(2024, 4, 14, 21, 9, 37, 24, DateTimeKind.Local).AddTicks(7930),
                            NoiKhoiHanh = "Buôn Ma Thuột",
                            PhuongTienDiChuyen = "Xe máy",
                            SoChoConNhan = 30,
                            SoLuongNguoiLon = 20,
                            SoLuongTreEm = 10,
                            TenTour = "Cà phê sân vườn",
                            ThoiGianBatDau = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKetThuc = new DateTime(2024, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TinhTrang = "Đang hoạt động"
                        });
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.AnhDoiTac", b =>
                {
                    b.HasOne("TourDuLichASAP.API.Models.Domain.DoiTac", "DoiTac")
                        .WithMany("AnhDoiTac")
                        .HasForeignKey("IdDoiTac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoiTac");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.AnhTour", b =>
                {
                    b.HasOne("TourDuLichASAP.API.Models.Domain.TourDuLich", "TourDuLich")
                        .WithMany()
                        .HasForeignKey("IdTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourDuLich");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.DanhGia", b =>
                {
                    b.HasOne("TourDuLichASAP.API.Models.Domain.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourDuLichASAP.API.Models.Domain.TourDuLich", "TourDuLich")
                        .WithMany()
                        .HasForeignKey("IdTour");

                    b.Navigation("KhachHang");

                    b.Navigation("TourDuLich");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.DatTour", b =>
                {
                    b.HasOne("TourDuLichASAP.API.Models.Domain.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourDuLichASAP.API.Models.Domain.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IdNhanVien");

                    b.HasOne("TourDuLichASAP.API.Models.Domain.TourDuLich", "TourDuLich")
                        .WithMany()
                        .HasForeignKey("IdTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("TourDuLich");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.DichVuChiTiet", b =>
                {
                    b.HasOne("TourDuLichASAP.API.Models.Domain.DatTour", "DatTour")
                        .WithMany()
                        .HasForeignKey("IdDatTour")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourDuLichASAP.API.Models.Domain.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("IdDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourDuLichASAP.API.Models.Domain.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourDuLichASAP.API.Models.Domain.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DatTour");

                    b.Navigation("DichVu");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.ThanhToan", b =>
                {
                    b.HasOne("TourDuLichASAP.API.Models.Domain.DatTour", "DatTour")
                        .WithMany()
                        .HasForeignKey("IdDatTour")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourDuLichASAP.API.Models.Domain.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourDuLichASAP.API.Models.Domain.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatTour");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.TourDuLich", b =>
                {
                    b.HasOne("TourDuLichASAP.API.Models.Domain.DoiTac", "DoiTac")
                        .WithMany()
                        .HasForeignKey("IdDoiTac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoiTac");
                });

            modelBuilder.Entity("TourDuLichASAP.API.Models.Domain.DoiTac", b =>
                {
                    b.Navigation("AnhDoiTac");
                });
#pragma warning restore 612, 618
        }
    }
}
